apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vllm
  namespace: inference
  annotations:
    kubernetes.io/ingress.class: 'gce'
    kubernetes.io/ingress.global-static-ip-name: '${GKE_STATIC_IP_NAME}'
    networking.gke.io/managed-certificates: 'vllm-cert'
spec:
  rules:
    - host: '${GKE_DOMAIN}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vllm
                port:
                  number: 80
