name: Deploy to Cloud Run

on:
  push:
    branches: [develop, stage, main]

jobs:
  dev:
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/_cloudrun_deploy.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit

  stage:
    if: ${{ github.ref == 'refs/heads/stage' || github.base_ref == 'stage' }}
    uses: ./.github/workflows/_cloudrun_deploy.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: stage
      ref: ${{ github.sha }}
    secrets: inherit

  prod:
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/_cloudrun_deploy.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
      ref: ${{ github.sha }}
    secrets: inherit

